name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build container
      uses: docker/build-push-action@v6
      with:
        context: .

  push:
    if: github.event_name != 'pull_request'
    needs:
    - container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Determine SHA
      id: sha
      run: echo "::set-output name=sha::$(git describe --always --tags --dirty)"
    - name: Build and push
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64, linux/arm64
        tags: ghcr.io/wavyland/wayvnc:latest, ghcr.io/wavyland/wayvnc:${{ steps.sha.outputs.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Determine digest
      run: echo ${{ steps.push.outputs.digest }}
